### ISSUE TITLE
Requesting Attachment of Documents

### ISSUE THREAD

**Issue by starabbu8123** [starabbu812/WhatsUpDevelopment#3]
Dear sir,it would be great if the app is capable of attaching the **Documents** as well.Kindly add this feature.

**Comment by starabbu812** [comment]
Dear starabbu8123,thanks for suggesting this feature.We will add and let u know.

**Comment by starabbu812** [comment]
Dear starabbu8123 thanks for your valuable suggestion,this feature is going to make our product great.
